Fix `control reaches end of non-void function` error in AsyncTlsToPlaintextSocket.h
Summary:
D33993697 is [failing to build](https://www.internalfb.com/intern/sandcastle/job/9007199823031571/) with this error:

```
mcrouter/lib/network/AsyncTlsToPlaintextSocket.h:106:19: error: control reaches end of non-void function [-Werror=return-type]
[CONTEXT]   106 |     LOG(FATAL) << "Unimplemented";
[CONTEXT]       |                   ^~~~~~~~~~~~~~~
```

Not sure why this broke now, but we can fix it pretty easily. `LOG(FATAL)` in glog will terminate the program, but the compiler doesn't realize this. We could either add a `[[noreturn]]` attribute here, or we could just return a value that will never be read. I opted to return a value because it has fewer caveats.

Reviewed By: DavidSnider

Differential Revision: D34117134

fbshipit-source-id: 362ad2284c521e178737a2258c6bce88884cc0e6