Fix double-free issue with Variant
Summary:
Copy and move constructors and assignment operators were broken, which I noticed
due to a new failing ASAN test: https://fburl.com/bbs0anbr

I wanted to just wrap `carbon::Variant` around `boost::variant`, but ended up with
this compilation error:
```
third-party-buck/gcc-4.9-glibc-2.20-fb/build/boost/e7e3e1f/include/boost/variant/detail/make_variant_list.hpp:40:27: error: too many template arguments for class template 'list'
```

So, rolling my own proper copy/move stuff for now.

Reviewed By: spalamarchuk

Differential Revision: D4752707

fbshipit-source-id: 898f9d707fea810f23c96d1e724df3e2fc8af58a