Fix for broken MWS builds + additional checks & error messages to avoid heap overflow described in diff D24568568
Summary:
Got notified of broken MWS builds. I recent change (D24568568 (https://github.com/facebook/mcrouter/commit/a9efeaac0181810e9b767c2380551ab36526e688)) in type of signed to unsigned type for normal_reply_index caused the following error:

```
mcrouter/routes/FailoverPolicy.h:413:34: error: result of comparison of unsigned expression >= 0 is always true [-Werror,-Wtautological-unsigned-zero-compare]

          if (normal_reply_index >= 0) {
              ~~~~~~~~~~~~~~~~~~ ^  ~
```
Removing the "if (normal_reply_index >= 0)" as it is no longer necessary.

Also, moving changes made in diff D24568568 (https://github.com/facebook/mcrouter/commit/a9efeaac0181810e9b767c2380551ab36526e688) to this diff as well.

Reviewed By: kkondaka

Differential Revision: D24842527

fbshipit-source-id: 805aee722cf4a97721a9cf2555d93dff969a4380