fix build breakage introduced in D2170719 (gcc 4.9)
Summary: mcrouter/lib/config/ConfigPreprocessor.cpp:164:72: error: converting
  to 'facebook::memcache::ConfigPreprocessor::Context {<skipped>}' from
  initializer list would use explicit constructor
  'std::unordered_map<{skipped}>'

We have to use direct-list-initialization instead of
copy-list-initialization as default `std::unordered_map` ctor is
explicit.

Test Plan: build and tests

Reviewed By: @pavlo-fb

Differential Revision: D2175968