Fix OSS mcpiper build: add -lasync, -lconcurrency to linker options (#350)
Summary:
`mcpiper` requires `-lasync` and `-lconcurrency` dependencies from fbthrift.

It's not entirely clear to me how this worked before; https://github.com/facebook/fbthrift/commit/99d6e035a6dc2a12dbe21dc6917c6ef173f976a1 is the only suspect upstream commit that might have broken things but I haven't looked much into it.

The build error symptom:

```
/bin/bash ../../libtool  --tag=CXX   --mode=link g++  -DLIBMC_FBTRACE_DISABLE -DDISABLE_COMPRESSION  -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2  -L/home/travis/build/facebook/mcrouter/mcrouter-install/install/lib -ljemalloc  -o mcpiper mcpiper-AnsiColorCodeStream.o mcpiper-Config.o mcpiper-FifoReader.o mcpiper-main.o mcpiper-McPiper.o mcpiper-MessagePrinter.o mcpiper-StyledString.o mcpiper-Util.o ../../lib/libmcrouter.a -lprotocol -lthriftcpp2 -lthriftprotocol -lrpcmetadata -ltransport -lthrift-core -lfizz -lfmt -lwangle -lfolly -lfizz -lsodium -lfolly -ldl -ldouble-conversion -lz -lssl -lcrypto -levent -lgflags -lglog  -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_filesystem       -lboost_program_options -lboost_system -lboost_regex       -lboost_thread -lpthread -pthread -ldl -lunwind       -lbz2 -llz4 -llzma -lsnappy -lzstd
libtool: link: g++ -DLIBMC_FBTRACE_DISABLE -DDISABLE_COMPRESSION -Wno-missing-field-initializers -Wno-deprecated -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -g -O2 -o mcpiper mcpiper-AnsiColorCodeStream.o mcpiper-Config.o mcpiper-FifoReader.o mcpiper-main.o mcpiper-McPiper.o mcpiper-MessagePrinter.o mcpiper-StyledString.o mcpiper-Util.o -pthread  -L/home/travis/build/facebook/mcrouter/mcrouter-install/install/lib -ljemalloc ../../lib/libmcrouter.a -lprotocol -lthriftcpp2 -lthriftprotocol -lrpcmetadata -ltransport -lthrift-core -lfmt -lwangle -lfizz -lsodium -lfolly -ldouble-conversion -lz -lssl -lcrypto -levent -lgflags -lglog -L/usr/lib/x86_64-linux-gnu -lboost_context -lboost_filesystem -lboost_program_options -lboost_system -lboost_regex -lboost_thread -lpthread -ldl -lunwind -lbz2 -llz4 -llzma -lsnappy -lzstd -pthread
/home/travis/build/facebook/mcrouter/mcrouter-install/install/lib/libthriftcpp2.a(ThriftServer.cpp.o): In function `apache::thrift::ThriftServer::setup()':
ThriftServer.cpp:(.text+0x2173): undefined reference to `apache::thrift::server::observerFactory_'
ThriftServer.cpp:(.text+0x219d): undefined reference to `apache::thrift::server::observerFactory_'
/home/travis/build/facebook/mcrouter/mcrouter-install/install/lib/libthriftcpp2.a(ThriftServer.cpp.o): In function `apache::thrift::ThriftServer::setupThreadManager()':
ThriftServer.cpp:(.text+0x2f58): undefined reference to `apache::thrift::concurrency::PriorityThreadManager::newPriorityThreadManager(unsigned long, bool)'
/home/travis/build/facebook/mcrouter/mcrouter-install/install/lib/libthriftcpp2.a(RocketThriftRequests.cpp.o): In function `folly::exception_wrapper apache::thrift::rocket::(anonymous namespace)::processFirstResponseHelper<apache::thrift::BinaryProtocolReader>(apache::thrift::ResponseRpcMetadata&, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> >&, int)':
RocketThriftRequests.cpp:(.text+0x4088): undefined reference to `apache::thrift::protocol::base64Decode(folly::Range<char const*>)'
RocketThriftRequests.cpp:(.text+0x43c1): undefined reference to `apache::thrift::protocol::base64Decode(folly::Range<char const*>)'
/home/travis/build/facebook/mcrouter/mcrouter-install/install/lib/libthriftcpp2.a(RocketThriftRequests.cpp.o): In function `folly::exception_wrapper apache::thrift::rocket::(anonymous namespace)::processFirstResponseHelper<apache::thrift::CompactProtocolReader>(apache::thrift::ResponseRpcMetadata&, std::unique_ptr<folly::IOBuf, std::default_delete<folly::IOBuf> >&, int)':
RocketThriftRequests.cpp:(.text+0x60f3): undefined reference to `apache::thrift::protocol::base64Decode(folly::Range<char const*>)'
RocketThriftRequests.cpp:(.text+0x643e): undefined reference to `apache::thrift::protocol::base64Decode(folly::Range<char const*>)'
/home/travis/build/facebook/mcrouter/mcrouter-install/install/lib/libthriftcpp2.a(GeneratedCodeHelper.cpp.o): In function `apache::thrift::detail::ap::helper<apache::thrift::BinaryProtocolReader, apache::thrift::BinaryProtocolWriter>::write_exn(char const*, apache::thrift::BinaryProtocolWriter*, int, apache::thrift::ContextStack*, apache::thrift::TApplicationException const&)':
GeneratedCodeHelper.cpp:(.text._ZN6apache6thrift6detail2ap6helperINS0_20BinaryProtocolReaderENS0_20BinaryProtocolWriterEE9write_exnEPKcPS5_iPNS0_12ContextStackERKNS0_21TApplicationExceptionE[_ZN6apache6thrift6detail2ap6helperINS0_20BinaryProtocolReaderENS0_20BinaryProtocolWriterEE9write_exnEPKcPS5_iPNS0_12ContextStackERKNS0_21TApplicationExceptionE]+0x109): undefined reference to `apache::thrift::ContextStack::handlerErrorWrapped(folly::exception_wrapper const&)'
/home/travis/build/facebook/mcrouter/mcrouter-install/install/lib/libthriftcpp2.a(GeneratedCodeHelper.cpp.o): In function `apache::thrift::detail::ap::helper<apache::thrift::CompactProtocolReader, apache::thrift::CompactProtocolWriter>::write_exn(char const*, apache::thrift::CompactProtocolWriter*, int, apache::thrift::ContextStack*, apache::thrift::TApplicationException const&)':
GeneratedCodeHelper.cpp:(.text._ZN6apache6thrift6detail2ap6helperINS0_21CompactProtocolReaderENS0_21CompactProtocolWriterEE9write_exnEPKcPS5_iPNS0_12ContextStackERKNS0_21TApplicationExceptionE[_ZN6apache6thrift6detail2ap6helperINS0_21CompactProtocolReaderENS0_21CompactProtocolWriterEE9write_exnEPKcPS5_iPNS0_12ContextStackERKNS0_21TApplicationExceptionE]+0x109): undefined reference to `apache::thrift::ContextStack::handlerErrorWrapped(folly::exception_wrapper const&)'
/home/travis/build/facebook/mcrouter/mcrouter-install/install/lib/libtransport.a(THttpParser.cpp.o): In function `apache::thrift::concurrency::Util::currentTime()':
THttpParser.cpp:(.text._ZN6apache6thrift11concurrency4Util11currentTimeEv[_ZN6apache6thrift11concurrency4Util11currentTimeEv]+0xa): undefined reference to `apache::thrift::concurrency::Util::currentTimeTicks(long)'
collect2: error: ld returned 1 exit status
Makefile:482: recipe for target 'mcpiper' failed
```

Pull Request resolved: https://github.com/facebook/mcrouter/pull/350

Reviewed By: disylh

Differential Revision: D23427213

Pulled By: stuclar

fbshipit-source-id: 72aa12f395aee936fcc94eacb56f58971ef83986