Add missing RoutingUtils.cpp to Makefile.am (#454)
Summary:
d80da5d817481ad64530a2f9a01612cf1a9ce879 adds new source file `routes/RoutingUtils.cpp` which is not included in `Makefile.am`

```
/bin/bash ./libtool  --tag=CXX   --mode=link sccache clang++-16 -DLIBMC_FBTRACE_DISABLE -DDISABLE_COMPRESSION -Wno-missing-field-initializers -Wno-deprecated-declarations -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -std=c++20 -g -O2 -L/home/imple/mcrouter/build/install/lib -latomic -z separate-code -lunwind -lxxhash -o mcrouter mcrouter-main.o mcrouter-RequestAclChecker.o mcrouter-StandaloneConfig.o mcrouter-StandaloneUtils.o libmcroutercore.a lib/libmcrouter.a -lthriftcpp2 -lserverdbginfo -ltransport -lthriftanyrep -lthrifttype -lthrifttyperep -lthriftprotocol -lrpcmetadata -lthriftannotation -lthriftmetadata -lasync -lconcurrency -lruntime -lthrift-core -lfmt -lwangle -lfolly -lfizz -lsodium -lfolly -liberty -ldl -ldouble-conversion -lz -lssl -lcrypto -levent -lgflags -lglog -L/usr/lib/aarch64-linux-gnu -lboost_context -lboost_filesystem -lboost_program_options -lboost_system -lboost_regex -lboost_thread -lpthread -pthread -ldl -lunwind       -lbz2 -llz4 -llzma -lsnappy -lzstd -latomic
libtool: link: sccache clang++-16 -DLIBMC_FBTRACE_DISABLE -DDISABLE_COMPRESSION -Wno-missing-field-initializers -Wno-deprecated-declarations -W -Wall -Wextra -Wno-unused-parameter -fno-strict-aliasing -std=c++20 -g -O2 -z separate-code -o mcrouter mcrouter-main.o mcrouter-RequestAclChecker.o mcrouter-StandaloneConfig.o mcrouter-StandaloneUtils.o -L/home/imple/mcrouter/build/install/lib -lxxhash libmcroutercore.a lib/libmcrouter.a -lthriftcpp2 -lserverdbginfo -ltransport -lthriftanyrep -lthrifttype -lthrifttyperep -lthriftprotocol -lrpcmetadata -lthriftannotation -lthriftmetadata -lasync -lconcurrency -lruntime -lthrift-core -lfmt -lwangle -lfizz -lsodium -lfolly -liberty -ldouble-conversion -lz -lssl -lcrypto -levent -lgflags -lglog -L/usr/lib/aarch64-linux-gnu -lboost_context -lboost_filesystem -lboost_program_options -lboost_system -lboost_regex -lboost_thread -lpthread -ldl -lunwind -lbz2 -llz4 -llzma -lsnappy -lzstd -latomic -pthread
/usr/bin/ld: libmcroutercore.a(libmcroutercore_a-McRouteHandleProvider-PoolRoute.o): in function `facebook::memcache::mcrouter::McRouteHandleProvider<facebook::memcache::MemcacheRouterInfo>::makePool(faceb ok::memcache::RouteHandleFactory<facebook::memcache::MemcacheRouteHandleIf>&, facebook::memcache::mcrouter::PoolFactory::PoolJson const&)':
/home/imple/mcrouter/build/mcrouter/mcrouter/routes/McRouteHandleProvider-inl.h:306: undefined reference to `facebook::memcache::mcrouter::getAdditionalFanout(folly::dynamic const&, facebook::memcache::McrouterOptions const&)'
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Pull Request resolved: https://github.com/facebook/mcrouter/pull/454

Reviewed By: lenar-f

Differential Revision: D64994625

Pulled By: alikhtarov

fbshipit-source-id: d6a0fe46981ac07d82a325f149bd3928605db715